### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by glyn** [cloudfoundry-incubator/cf-lager#1]
Although cf-lager is a small wrapper, its purpose and intended usage is not entirely obvious.

As far as purpose is concerned, what are the benefits of using cf-lager over calling lager directly?

On usage, is it intended that AddFlags be called in each main program that uses cf-lager or is this better called during static initialisation (an init func)? Where should flags.Parse be called, since doing this in static initialisation tends to wreak havoc with test executable flags?

Also, is there a recommended technique for propagating log levels across process boundaries? E.g. is there a standard way of extracting the current log level and adding the appropriate flag value to the invocation of a process?

It would be great to capture some or all of this information in the README.

**Comment by jenspinney** [comment]
Hi Glyn,

We added some more documentation and an example of using the library. If you think we still need to go into more detail, please let us know. I think the questions about whether to include flags in a main function or in an init function are general go questions and may be outside the scope of the documentation for this small library.

For your question about propagating log levels across process boundaries, you can call `GetMinLevel()` on the ReconfigurableSink to figure out the current value of the log level. We included this in the example code we added to the README.

Thanks!
@jenspinney and @joachimvaldez

**Comment by glyn** [comment]
Good stuff. Thanks @jenspinney and @joachimvaldez!
